---
- hosts: lnbits
  roles:
    - role: bleetube.lnbits
      tags: lnbits
  tasks:
    - import_tasks: ../nginx/lnbits/nginx_conf.yml
      become: yes
      tags: nginx
      when: ansible_os_family != 'Archlinux' # still nginx 1.24 which doesn't support newer http2 syntax