---
- hosts: postgresql
  become: true

  vars:
    postgresql_apt_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"

  pre_tasks:
    - name: Assert all database passwords have been configured.
      ansible.builtin.assert:
        that:
          - item.pass is defined
          - item.pass != ''
        fail_msg: "FAILED: Database password for {{ item.name }} is not configured."
      loop: "{{ postgresql_users }}"
      no_log: true

  roles:
    - role: anxs.postgresql
