---
- hosts: strfry
  gather_facts: yes
  roles:
    - role: bleetube.strfry
      tags: strfry
    - role: bleetube.nodejs
      tags: nodejs
    - role: bleetube.snort
      tags: snort
  tasks:
    - import_tasks: ../nginx/strfry/nginx_conf.yml
      tags: nginx
      become: yes
      # nginx on Arch will throw an error: "pid" directive is duplicate
      #when: ansible_os_family != 'Archlinux'
