---
- name: Ensure directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/home/{{ local_user }}/.config/systemd/user"
    - "{{ scripts_dir }}"

# updates: cp -v ~/ai/text-generation-webui/settings.yaml ~/ops/brenise.com/infra/ansible/playbooks/host_tasks/files/textgen/
# updates: cp -v ~/.config/systemd/user/textgen.service ~/ops/brenise.com/infra/ansible/playbooks/host_tasks/files/textgen/
- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: files/textgen/settings.yaml, dest: "{{ textgen_dir }}" }
    - { src: files/textgen/textgen.service, dest: "/home/{{ local_user }}/.config/systemd/user" }

# updates: cp -v ~/bin/textgen-server.sh ~/ops/brenise.com/infra/ansible/playbooks/host_tasks/files/textgen/
- name: Copy script(s)
  ansible.builtin.copy:
    src: files/textgen/textgen-server.sh
    dest: "{{ scripts_dir }}"
    mode: '0755'

- name: Reload systemd user units
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Enable system user unit
  ansible.builtin.systemd:
    name: textgen.service
    enabled: yes
    state: started
    scope: user