- hosts: wartortle.satstack.net
  become: true

  handlers:
    - name: restart dojo_exporter
      ansible.builtin.systemd: name=dojo_exporter.service state=restarted

  tasks:
    - name: dojo_exporter | Create a user
      ansible.builtin.user:
        name: "{{ dojo_exporter_user|default('dojo-exp') }}"
        home: "{{ dojo_exporter_home|default('/opt/dojo_exporter') }}"
        shell: /bin/bash
        createhome: yes
        password: '!'

    - include_tasks:
        file: install.yml
        apply:
          become: true
          become_user: dojo-exp

    - name: dojo_exporter | Ensure service unit
      ansible.builtin.template:
        src: dojo_exporter.service.j2
        dest: /etc/systemd/system/dojo_exporter.service
        owner: "{{ dojo_exporter_user|default('dojo-exp') }}"

    - name: dojo_exporter | Ensure service is running
      ansible.builtin.systemd:
        name: dojo_exporter.service
        enabled: true
        state: started
        daemon_reload: yes

    - import_tasks: nginx_conf.yml
      tags: nginx