---
# prefer lego because synapse uses a version of python3-zope.interface that conflicts with certbot
acme_email: acme@bitcoiner.social
acme_domains:
# - { domain: "{{ inventory_hostname }}", provider: namecheap }
  - { domain: offchain.pub, provider: namecheap }
