---
# https://code.samourai.io/dojo/samourai-dojo/-/tree/develop/docker/my-dojo/nginx/mainnet.conf
- name: Wiki.js | Configure nginx
  ansible.builtin.import_role:
    name: nginx_core.nginx_config
  vars:
    nginx_config_http_template_enable: true
    nginx_config_http_template:
      - template_file: http/default.conf.j2
        deployment_location: "/etc/nginx/conf.d/wikijs_{{ inventory_hostname }}.conf"
        backup: false
        config:
          servers:
            - core:
                listen:
                  - address: "{{ default_interface_ipv4_address|default(ansible_default_ipv4.address) }}:{{ wikijs_https_port|default(4441) }} ssl"
                include:
                  - "/etc/nginx/acme_{{ inventory_hostname }}.conf"
              log:
                access:
                  - off
              locations:
                - location: /
                  proxy:
                    pass: "http://127.0.0.1:{{ wikijs_http_port|default(8041) }}"
                    http_version: '1.1'
                    set_header:
                    - field: Host
                      value: $http_host
                    - field: Connection
                      value: $connection_upgrade
                    - field: Upgrade
                      value: $http_upgrade