---
- hosts: rhyperior.bitcoiner.social
  roles:
    - role: bleetube.castopod
      tags: castopod
  tasks:
    - import_tasks: ../../nginx/castopod/nginx_conf.yml
      tags: nginx
      become: yes