---
- hosts: all

  tasks:
    - name: "Ensure normal user exists called: {{ sysadmin_username }}."
      ansible.builtin.user:
        name: "{{ sysadmin_username }}"
        shell: /bin/bash
      register: user_for_sysadmin

    - name: Ensure .ssh directory
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: '0700'
      become: yes
      become_user: "{{ sysadmin_username }}"
#     when: user_for_sysadmin.changed

    - name: "Copy ssh pubkey for {{ sysadmin_username }}"
      ansible.builtin.copy:
        src: ~/.ssh/id_ed25519.pub
        dest: ~/.ssh/authorized_keys
      become: yes
      become_user: "{{ sysadmin_username }}"
#     when: user_for_sysadmin.changed

    - name: Ensure doas is installed. 
      ansible.builtin.package:
        name: doas
        state: present

    - name: Configure doas.
      ansible.builtin.template: 
        src: doas.conf.j2
        dest: /etc/doas.conf

#   - name: Try to remove sudo.
#     ansible.builtin.package:
#       name: sudo
#       state: absent
#     tags: test
#     environment:
#       SUDO_FORCE_REMOVE: yes
