---
# https://github.com/prometheus/node_exporter/releases
node_exporter_version: latest

# https://github.com/prometheus/prometheus/releases
prometheus_version: latest

# https://github.com/prometheus/blackbox_exporter/releases
blackbox_exporter_version: '0.24.0'

# https://github.com/prometheus/alertmanager/releases
alertmanager_version: latest

# https://github.com/grafana/grafana/releases
#grafana_version: 9.5.13
grafana_version: latest

# https://git.xenrox.net/~xenrox/ntfy-alertmanager
ntfy_alertmanager_version: v0.3.0

# https://go.dev/dl/
golang_version: "1.21.1" # gantsign.golang
#golang_version: "1.20.4" # gantsign.golang

# https://grafana.com/grafana/dashboards/1860-node-exporter-full/?tab=revisions
grafana_node_dashboard_version: 32

# https://mariadb.org/mariadb/all-releases/
mariadb_use_official_repo_version: "10.11"

# https://github.com/mempool/mempool/releases
#mempool_version: v2.5.0 # TODO: move to nix

# https://github.com/Ride-The-Lightning/RTL/releases
#rtl_version: "0.14.1"
rtl_version: "0.15.0"

# https://github.com/dgtlmoon/changedetection.io/releases
changedetection_version: "0.45.5"

# https://hub.docker.com/_/nextcloud
nextcloud_version: 27-fpm-alpine

# https://code.samourai.io/dojo/samourai-dojo/-/releases
samourai_dojo_version: "1.21.0"

# https://github.com/Requarks/wiki/pkgs/container/wiki
wikijs_version: latest

# https://hub.docker.com/r/castopod/app/tags
# https://code.castopod.org/adaures/castopod/-/releases
castopod_version: "1.4.7"
#castopod_version: "1.5.2"
#castopod_version: "1.6.2"
#castopod_version: latest

# https://github.com/lightningnetwork/lnd/releases
#lnd_version: 0.17.0-beta.rc6
#lnd_version: latest # works, but (rightly) installs stable rather than release candidates

# https://github.com/hoytech/strfry/tags
strfry_version: master

# https://git.v0l.io/Kieran/snort/releases
#snort_version: v0.1.20 # We must merge our branch for updates, the role follows a branch