---
# https://github.com/prometheus/node_exporter/releases
node_exporter_version: latest

# https://github.com/prometheus/prometheus/releases
prometheus_version: latest

# https://github.com/prometheus/blackbox_exporter/releases
blackbox_exporter_version: '0.24.0'

# https://github.com/prometheus/alertmanager/releases
alertmanager_version: latest

# https://github.com/grafana/grafana/releases
grafana_version: latest

# https://git.xenrox.net/~xenrox/ntfy-alertmanager
ntfy_alertmanager_version: v0.2.0

# https://go.dev/dl/
golang_version: "1.20.4" # gantsign.golang

# https://grafana.com/grafana/dashboards/1860-node-exporter-full/?tab=revisions
grafana_node_dashboard_version: 31

# https://mariadb.org/mariadb/all-releases/
mariadb_use_official_repo_version: "10.11"

# https://github.com/mempool/mempool/releases
# ansible-playbook playbooks/host_tasks/wartortle.satstack.net.yml --tags podman
mempool_version: v2.5.0

# https://github.com/Ride-The-Lightning/RTL/releases
rtl_version: "0.14.0"