---
# TODO: synapse settings template, TURN server, admin-api panel, lockdown admin URI. See README.md
# https://matrix-org.github.io/synapse/latest/setup/installation.html?highlight=register_new_matrix_user#registering-a-user
- hosts: pancham.brenise.com
  become_method: doas
  become_user: blee
  become: true

  vars:
    synapse_version: v1.78.0
    synapse_server_name: brenise.com
    peertube_version: v5.0.1
    peertube_domain: blee.tube
    peertube_root_path: /var/www/peertube
    peertube_secret: "{{ lookup('ansible.builtin.env', \"{{ inventory_hostname_short }}_PEERTUBE_SECRET\") }}"
    peertube_postgres_password: "{{ lookup('ansible.builtin.env', \"{{ inventory_hostname_short }}_PEERTUBE_POSTGRES_PASSWORD\") }}"
    peertube_smtp_password: "{{ lookup('ansible.builtin.env', \"{{ inventory_hostname_short }}_PEERTUBE_SMTP_PASSWORD\") }}"
    synapse_postgres_password: "{{ lookup('ansible.builtin.env', \"{{ inventory_hostname_short }}_SYNAPSE_POSTGRES_PASSWORD\") }}"
    tandoor_postgres_password: "{{ lookup('ansible.builtin.env', \"{{ inventory_hostname_short }}_TANDOOR_POSTGRES_PASSWORD\") }}"
    tandoor_secret_key: "{{ lookup('ansible.builtin.env', \"{{ inventory_hostname_short }}_TANDOOR_SECRET_KEY\") }}"

  pre_tasks:
    - name: Assert all secrets have been defined.
      ansible.builtin.assert:
        that:
          - item is defined
          - item != ''
        fail_msg: "FAILED: Secrets are not configured."
        quiet: true
      no_log: true
      loop:
        - "{{ peertube_secret }}"
        - "{{ peertube_postgres_password }}"
        - "{{ peertube_smtp_password }}"
        - "{{ tandoor_secret_key }}"
        - "{{ tandoor_postgres_password }}"

  tasks:
    - import_tasks: tasks/setup-tandoor.yml
      tags: tandoor
    - import_tasks: tasks/setup-peertube.yml
      tags: peertube
    - import_tasks: tasks/setup-synapse.yml
      tags: synapse
    - import_tasks: tasks/setup-docker.yml
      tags: docker

    - name: Copy frontend assets from container volume to be readable by nginx.
      ansible.builtin.copy:
        remote_src: true
        src: /var/lib/docker/volumes/docker_assets/_data/
        dest: "{{ peertube_root_path }}/peertube-latest/client/dist"
      tags: upgrade
      become: false

    # https://matrix-org.github.io/synapse/latest/usage/configuration/homeserver_sample_config.html
    # Synapse will generate a new signing key if it doesn't find one.
    # TODO: make this a template
    - name: Generate Synapse initial configuration and signing-key.
      ansible.builtin.command:
        cmd: docker-compose run synapse generate
        chdir: "{{ ansible_env.HOME }}/docker"
        creates: /var/compose/synapse/config/homeserver.yaml
      tags: test
