---
- name: RTL | Assert all secrets have been configured.
  ansible.builtin.assert:
    that:
      - item is defined
      - item != ''
    fail_msg: "FAILED: Secret {{ item }} is not configured."
    quiet: true
  loop:
    - rtl_config.APP_PASSWORD
  no_log: true

# Based on: https://github.com/Ride-The-Lightning/RTL/blob/master/docker/docker-compose.yml
- name: RTL | Create containers
  register: output
  containers.podman.podman_container:
    name: RTL 
    image: "shahanafarooqui/rtl:{{ rtl_version|default(latest) }}"
    env: "{{ rtl_config }}"
    recreate: true
    state: present
    volumes:
      - /var/compose/rtl:/data
      - /var/compose/.secrets/lightningd:/certs
    ports:
      - "127.0.0.1:{{ rtl_http_port|default(8037)}}:3000"

- ansible.builtin.debug:
    var: output
  tags: upgrade

- name: RTL | Generate systemd unit file for containers
  containers.podman.podman_generate_systemd:
    name: RTL
    dest: ~/.config/systemd/user/
    restart_policy: on-failure
    restart_sec: 60
    stop_timeout: 60

- name: RTL | Ensure container(s) are enabled in systemd, but stopped so we can use "recreate" in podman_container.
  ansible.builtin.systemd:
    name: container-RTL
    scope: user
    daemon_reload: true
    state: stopped
    enabled: true

- name: RTL | Start the container(s) with systemd, so systemd will know the state of the container(s) moving forward.
  ansible.builtin.systemd:
    name: container-RTL
    scope: user
    state: started