---
- hosts: docker
  become_user: "{{ sysadmin_username }}"
  become: true

  pre_tasks:
    - name: Ensure a directory in the user home dir for docker-compose.
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/docker"
        state: directory

- import_playbook: wartortle/main.yml

  tasks:
    - name: Create and start services
      community.docker.docker_compose:
        project_src: "{{ ansible_env.HOME }}/docker"
#       build: true
      register: output
      when: git_repository.changed
      tags: upgrade

    - ansible.builtin.debug:
        var: output
      tags: upgrade
