---
- hosts: docker

  tasks:
    - name: Use docker-compose version 3
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/docker/docker-compose.yml"
        create: yes
        block: |
          version: "3"
          services:

    - name: Ensure an environment variable file exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/docker/.env"
        state: touch
        mode: '0600'
      changed_when: false