---
- hosts: wartortle.satstack.net

  tasks:
    - name: Assert mempool secrets have been defined.
      ansible.builtin.assert:
        that:
          - item is defined
          - item != ''
        fail_msg: "FAILED: Secrets for mempool are not configured."
        quiet: true
      no_log: true
      loop:
        - "{{ mempool_core_rpc_password }}"
        - "{{ mempool_db_password }}"
      tags: env

      # Based on: https://github.com/mempool/mempool/blob/master/docker/docker-compose.yml
    - name: Add mempool containers to docker-compose.yml
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/docker/docker-compose.yml"
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR MEMPOOL"
        block: |
          #
            mempool-frontend:
              container_name: mempool-frontend
              build:
                context: {{ ansible_env.HOME }}/src/mempool/frontend
                dockerfile: {{ ansible_env.HOME }}/src/mempool/docker/frontend/Dockerfile
              image: mempool/frontend:latest
              environment:
                FRONTEND_HTTP_PORT: "8080"
                BACKEND_MAINNET_HTTP_HOST: "mempool-backend"
              user: "1000:1000"
              restart: on-failure
              stop_grace_period: 1m
              command: "./wait-for 172.17.0.1:3306 --timeout=720 -- nginx -g 'daemon off;'"
              ports:
                - 127.0.0.1:4432:8080
            mempool-backend:
              container_name: mempool-backend
              build:
                context: {{ ansible_env.HOME }}/src/mempool/backend
                dockerfile: {{ ansible_env.HOME }}/src/mempool/docker/backend/Dockerfile
              image: mempool/backend:latest
              env_file:
                - .env
              user: "1000:1000"
              restart: on-failure
              stop_grace_period: 1m
              command: "./wait-for-it.sh 172.17.0.1:3306 --timeout=720 --strict -- ./start.sh"
              volumes:
                - /var/composer/mempool/cache:/backend/cache
                #- /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
          #

    - name: Configure mempool variables
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/docker/.env"
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR MEMPOOL"
        block: |
          CORE_RPC_HOST=192.168.0.42
          CORE_RPC_PORT=8332
          CORE_RPC_USERNAME=mempool
          CORE_RPC_PASSWORD='{{ mempool_core_rpc_password }}'
          DATABASE_ENABLED=true
          DATABASE_HOST=192.168.0.42
          DATABASE_DATABASE=mempool
          DATABASE_USERNAME=mempool
          DATABASE_PASSWORD='{{ mempool_db_password }}'
          STATISTICS_ENABLED="true"
          MEMPOOL_BACKEND=electrum
          ELECTRUM_HOST=192.168.0.42
          ELECTRUM_PORT=50001
          ELECTRUM_TLS_ENABLED=false

    - name: Clone repository
      ansible.builtin.git:
        repo: 'https://github.com/mempool/mempool.git'
        dest: "{{ ansible_env.HOME }}/src/mempool"
        version: "{{ mempool_version }}"
      register: git_repository
      tags: upgrade

    - name: Ensure data directory.
      ansible.builtin.file:
        path: /var/compose/mempool
        state: directory

    - name: Ensure writable cache directory.
      ansible.builtin.file:
        path: /var/compose/mempool/cache
        state: directory
        mode: '0777'

    - name: Create and start services
      community.docker.docker_compose:
        project_src: "{{ ansible_env.HOME }}/docker"
        build: false   # (docker-compose build fails)
      register: output
      when: git_repository.changed
      tags: upgrade

    - ansible.builtin.debug:
        var: output
      tags: upgrade
