---
blackbox_exporter_configuration_modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: []
      method: GET
      preferred_ip_protocol: ip4
      fail_if_not_ssl: true

  tcp_probe:
    prober: tcp
    timeout: 5s

  smtp_starttls:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
        - expect: "^220 ([^ ]+) ESMTP (.+)$"
        - send: "EHLO prober\r"
        - expect: "^250-STARTTLS"
        - send: "STARTTLS\r"
        - expect: "^220"
        - starttls: true
        - send: "EHLO prober\r"
#       - expect: "^250-AUTH"
        - expect: "^250-DSN" # mail server doesn't prompt for authentication
        - send: "QUIT\r"

  http_404:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [ 404 ]
      method: GET
      preferred_ip_protocol: ip4
      fail_if_not_ssl: true
