---
# https://github.com/fauust/ansible-role-mariadb/blob/main/defaults/main.yml
mariadb_use_official_repo: true
#mariadb_use_official_repo_version: "10.10"
# You can only bind to one address. https://serverfault.com/q/139323/70156
mariadb_bind_address: 0.0.0.0
mariadb_databases:
  - name: mempool
    collation: utf8_general_ci
    encoding: utf8
    replicate: false
  - name: samourai
    collation: utf8_general_ci
    encoding: utf8
    replicate: false
# - name: nextcloud
#   collation: utf8_general_ci
#   encoding: utf8
#   replicate: false

# Both localhost and * (all hosts) are mutually exclusive: https://stackoverflow.com/q/10823854/9290
mariadb_users:
  - name: mempool
    host: localhost
    password: "{{ lookup('ansible.builtin.env', 'wartortle_MEMPOOL_MARIADB_PASSWORD') }}"
    priv: "mempool.*:ALL"
    state: present
  - name: mempool
    host: '%'
    password: "{{ lookup('ansible.builtin.env', 'wartortle_MEMPOOL_MARIADB_PASSWORD') }}"
    priv: "mempool.*:ALL"
    state: present

  - name: samourai
    host: localhost
    password: "{{ lookup('ansible.builtin.env', 'wartortle_SAMOURAI_MARIADB_PASSWORD') }}"
    priv: "samourai.*:ALL"
    state: present
  - name: samourai
    host: '%'
    password: "{{ lookup('ansible.builtin.env', 'wartortle_SAMOURAI_MARIADB_PASSWORD') }}"
    priv: "samourai.*:ALL"
    state: present

# - name: nextcloud
#   host: localhost
#   password: "{{ lookup('ansible.builtin.env', 'wartortle_NEXTCLOUD_MARIADB_PASSWORD') }}"
#   priv: "nextcloud.*:ALL"
#   state: present
# - name: nextcloud
#   host: '%'
#   password: "{{ lookup('ansible.builtin.env', 'wartortle_NEXTCLOUD_MARIADB_PASSWORD') }}"
#   priv: "nextcloud.*:ALL"
#   state: present

# https://mariadb.com/kb/en/mariadb-memory-allocation/
# Nextcloud: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml#L6C14-L6C89
mariadb_innodb_raw: |
  # InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.
  # Read the manual for more InnoDB related options. There are many!
    innodb_buffer_pool_size = 512M
    key_buffer_size = 10M
    transaction_isolation=READ-COMMITTED # samourai and nextcloud
    #sql_mode="NO_ENGINE_SUBSTITUTION" # samourai
    #log_bin=binlog # nextcloud
    #binlog-format=ROW # nextcloud