nextcloud_https_port: 4440
nextcloud_http_port: 8040
nextcloud_fpm_upstream: "127.0.0.1:9000"

nextcloud_create_volumes: []

nextcloud_nginx_root: /var/compose/nextcloud

nextcloud_volumes:
  - "{{ nextcloud_nginx_root }}:/var/www/html"
  - /var/run/postgresql:/var/run/postgresql

# https://github.com/nextcloud/docker/blob/master/README.md#auto-configuration-via-environment-variables
nextcloud_config:
  NEXTCLOUD_TRUSTED_DOMAINS: "{{ inventory_hostname }}:{{ nextcloud_https_port }}"
  # This is supposedly "empty by default" but is coming up with http://localhost
  OVERWRITECLIURL: "https://{{ inventory_hostname }}:{{ nextcloud_https_port }}"

  POSTGRES_HOST: /var/run/postgresql
  POSTGRES_DB: nextcloud
  POSTGRES_USER: nextcloud
  POSTGRES_PASSWORD: "{{ lookup('ansible.builtin.env', 'wartortle_NEXTCLOUD_POSTGRES_PASSWORD') }}"

  # nextcloud throws 500 errors with this enabled
# REDIS_HOST: host.containers.internal
# REDIS_HOST: host.containers.internal:6379

# SMTP_HOST: ""
# SMTP_SECURE: ""  # ssl to use SSL, or tls zu use STARTTLS
# SMTP_PORT: "" # (25, 465 for SSL, 587 for STARTTLS)
# SMTP_AUTHTYPE: ""
# SMTP_NAME: ""
# SMTP_PASSWORD: ""
# MAIL_FROM_ADDRESS: ""
# MAIL_DOMAIN: ""