---
# https://github.com/ANXS/postgresql/blob/master/defaults/main.yml
# https://github.com/ANXS/postgresql/pull/534
postgresql_version: 15

postgresql_listen_addresses: []
postgresql_autovacuum: on
postgresql_synchronous_commit: off
postgresql_password_encryption: scram-sha-256
postgresql_default_auth_method_hosts: scram-sha-256
#postgresql_full_page_writes: off #temp

# pgtune automation is broken.
# https://github.com/ANXS/postgresql/issues/201
#postgresql_pgtune: true
# Use the web app and prefix each variable with postgresql_
# https://pgtune.leopard.in.ua/

# DB Version: 15
# OS Type: linux
# DB Type: web
# Total Memory (RAM): 8 GB
# CPUs num: 4
# Data Storage: ssd

postgresql_max_connections: 200
postgresql_shared_buffers: 2GB
postgresql_effective_cache_size: 6GB
postgresql_maintenance_work_mem: 512MB
postgresql_checkpoint_completion_target: 0.9
postgresql_wal_buffers: 16MB
postgresql_default_statistics_target: 100
postgresql_random_page_cost: 1.1
postgresql_effective_io_concurrency: 200
postgresql_work_mem: 5242kB
postgresql_min_wal_size: 1GB
postgresql_max_wal_size: 4GB
postgresql_max_worker_processes: 4
postgresql_max_parallel_workers_per_gather: 2
postgresql_max_parallel_workers: 4
postgresql_max_parallel_maintenance_workers: 2

# Authentication (pg_hba.conf)
postgresql_pg_hba_default:
  - { type: local, database: all, user: postgres, address: "", method: peer, comment: '"local" is for Unix domain socket connections only' }
  - { type: local, database: all, user: all, address: "", method: "{{ postgresql_default_auth_method_hosts }}", comment: '"local" is for Unix domain socket connections only' }
  - { type: host,  database: all, user: all, address: "127.0.0.1/32", method: "{{ postgresql_default_auth_method_hosts }}", comment: "IPv4 local connections:" }
  - { type: host,  database: all, user: all, address: "172.16.0.0/12", method: "{{ postgresql_default_auth_method_hosts }}", comment: "Docker container connections:"  }
  - { type: host,  database: all, user: all, address: "::1/128", method: "{{ postgresql_default_auth_method_hosts }}", comment: "IPv6 local connections:" }

# It's wierd they don't have a simple list for adding scram authentication: 
# https://github.com/ANXS/postgresql/blob/63a22322fdb769a4649aea3ff936ce6aea0d963a/templates/pg_hba.conf.j2#L28

# Troubleshoot authentication: tail -f /var/log/postgresql/postgresql-13-main.log
postgresql_users:
  - name: wikijs
    pass: "{{ lookup('ansible.builtin.env', 'wartortle_WIKIJS_POSTGRES_PASSWORD') }}"
    encrypted: yes
    state: present
  - name: nextcloud
    pass: "{{ lookup('ansible.builtin.env', 'wartortle_NEXTCLOUD_POSTGRES_PASSWORD') }}"
    encrypted: yes
    state: present
  - name: testnet
    pass: "{{ lookup('ansible.builtin.env', 'wartortle_TESTNET_POSTGRES_PASSWORD') }}"
    encrypted: yes
    state: present

postgresql_databases:
  - name: wikijs
    owner: wikijs
    state: present
    lc_collate: C.UTF-8
    lc_ctype: C.UTF-8
  - name: nextcloud
    owner: nextcloud
    state: present
  - name: testnet
    owner: testnet
    state: present
#   hstore: yes         # flag to install the hstore extension on this database (yes/no)
#   uuid_ossp: yes      # flag to install the uuid-ossp extension on this database (yes/no)
#   citext: yes         # flag to install the citext extension on this database (yes/no)
#   encoding: "UTF-8"   # override global {{ postgresql_encoding }} variable per database
#   lc_collate: "en_US.UTF-8"   # override global {{ postgresql_locale }} variable per database
#   lc_ctype: "en_US.UTF-8"     # override global {{ postgresql_ctype }} variable per database

#postgresql_database_schemas:
#  - database: mealie
#    schema: mealie
#    state: present

#postgresql_user_privileges:
#  - name: mealie
#    db: mealie
#    priv: "ALL"
#    role_attr_flags: "CREATEDB"
