rtl_http_port: 8038
rtl_http_port: 4438

# See: https://github.com/Ride-The-Lightning/RTL/blob/master/.github/docs/Application_configurations.md
rtl_config:
  APP_PASSWORD: "{{ lookup('ansible.builtin.env', 'wartortle_RTL_MULTI_PASS_HASHED') }}"
  RTL_CONFIG_PATH: /RTL

  HOST: 192.168.0.27
  MACAROON_PATH: /shared
  LN_SERVER_URL: https://squirtle.satstack.net:4445
  CONFIG_PATH: ''
  LN_IMPLEMENTATION: CLT
  SWAP_SERVER_URL: https://${LIGHTNING_HOST}:${LIGHTNING_LOOP_PORT}
  SWAP_MACAROON_PATH: /shared
  BOLTZ_SERVER_URL: https://${BOLTZ_HOST}:${BOLTZ_PORT}
  BOLTZ_MACAROON_PATH: /shared
  RTL_SSO: 0
  RTL_COOKIE_PATH: ''
  LOGOUT_REDIRECT_LINK: ''
  RTL_CONFIG_PATH: /RTL
  BITCOIND_CONFIG_PATH: ''
  CHANNEL_BACKUP_PATH: /shared/lnd/backup
  ENABLE_OFFERS: false
  ENABLE_PEERSWAP: false