--- # 
rtl_http_port: 8038
rtl_https_port: 4438

# See: https://github.com/Ride-The-Lightning/RTL/blob/master/.github/docs/Application_configurations.md
rtl_config:
  APP_PASSWORD: "{{ lookup('ansible.builtin.env', 'wartortle_RTL_PASSWORD') }}"
  RTL_CONFIG_PATH: /data
  LN_IMPLEMENTATION: CLN
  LN_SERVER_URL: https://squirtle.satstack.net:4445
 #MACAROON_PATH: /certs
  RTL_SSO: 0
  RUNE_PATH: /certs/.rune

# https://www.peerswap.dev/
# ENABLE_PEERSWAP: false
# SWAP_SERVER_URL: https://${LIGHTNING_HOST}:${LIGHTNING_LOOP_PORT}
# SWAP_MACAROON_PATH: /certs

# https://boltz.exchange/ (third party service)
# BOLTZ_SERVER_URL: https://${BOLTZ_HOST}:${BOLTZ_PORT}
# BOLTZ_MACAROON_PATH: /certs
