---
- name: RLT - Configure nginx
  ansible.builtin.import_role:
    name: nginx_core.nginx_config
  tags: nginx
  vars:
    nginx_config_http_template_enable: true
    nginx_config_http_template:
      - template_file: http/default.conf.j2
        deployment_location: "/etc/nginx/conf.d/rtl_{{ inventory_hostname }}.conf"
        backup: false
        config:
          servers:
            - core:
                listen:
                  - address: "{{ default_interface_ipv4_address|default(ansible_default_ipv4.address) }}:{{ rtl_https_port|default(4438) }} ssl"
                include:
                  - "/etc/nginx/acme_{{ inventory_hostname }}.conf"
              http2:
                enabled: true
              locations:
                - location: /
                  proxy:
                    pass: "http://127.0.0.1:{{ rtl_http_port|default(8038) }}"
                    http_version: '1.1'
                    set_header:
                      - field: Host
                        value: $http_host
