---
- hosts: wartortle.satstack.net

  vars:
    container_playbooks: ../../containers

  tasks:
    - import_tasks: tasks/setup.yml
      tags: setup

    - import_tasks: tasks/podman.yml
      tags: podman

    - include_tasks:
        file: tasks/nginx_conf.yml
        apply:
          become: true
      tags: nginx