---
- name: Configure nginx for mempool
  ansible.builtin.import_role:
    name: nginx_core.nginx_config
  tags: nginx
  become: true
  vars:
    nginx_config_http_template_enable: true
    nginx_config_http_template:
      - template_file: http/default.conf.j2
        deployment_location: "/etc/nginx/conf.d/mempool_{{ inventory_hostname }}.conf"
        backup: false
        config:
          servers:
            - core:
                listen:
                  - address: "{{ default_interface_ipv4_address|default(ansible_default_ipv4.address) }}:{{ mempool_https_port|default(4434)}} ssl"
                include:
                  - "/etc/nginx/acme_{{ inventory_hostname }}.conf"
              log:
                access:
                  - off
              http2:
                enabled: true
              locations:
                - location: /
                  proxy:
                    pass: "http://127.0.0.1:{{ mempool_http_port|default(8034)}}"
                    buffering: false
                    http_version: '1.1'
                    set_header:
                    - field: Host
                      value: $http_host
                    - field: Connection
                      value: $connection_upgrade
                    - field: Upgrade
                      value: $http_upgrade
                    - field: X-Real-IP
                      value: $remote_addr
