---
# Based on: https://github.com/mempool/mempool/blob/master/docker/docker-compose.yml
- name: Start mempool-backend with inline definition
  register: output
  containers.podman.podman_container:
    name: mempool-backend
    image: "mempool/backend:{{ mempool_version|default(latest) }}"
    state: present
#   restart: on-failure
#   stop_grace_period: 1m
    command: "./wait-for-it.sh {{ mempool_config.DATABASE_HOST }}:3306 --timeout=720 --strict -- ./start.sh"
#   user: "1000:1000"
    env: "{{ mempool_config }}"
    recreate: true
    volumes:
      - /var/compose/mempool/cache:/backend/cache
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

- name: Start mempool-frontend with inline definition
  register: output
  containers.podman.podman_container:
    name: mempool-frontend
    image: "mempool/frontend:{{ mempool_version|default(latest) }}"
    state: stopped
    ports:
      - "127.0.0.1:{{ mempool_listen_port|default(4434)}}:8080"
#   restart: on-failure
#   stop_grace_period: 1m
#   command: "./wait-for {{ mempool_config.DATABASE_HOST }}:3306 --timeout=720 -- nginx -g 'daemon off;'"
    env:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "mempool-backend"

- ansible.builtin.debug:
    var: output
  tags: upgrade

- name: Generate systemd unit file for mempool containers
  containers.podman.podman_generate_systemd:
    name: "{{ item }}"
    dest: ~/.config/systemd/user/
    wants: mariadb.service
  loop:
#   - mempool-frontend
    - mempool-backend

- name: Ensure mempool containers are started and enabled
  ansible.builtin.systemd:
    name: "container-{{ item }}"
    scope: user
    daemon_reload: true
    state: started
    enabled: true
  loop:
#   - mempool-frontend
    - mempool-backend