---
# Based on: https://github.com/mempool/mempool/blob/master/docker/docker-compose.yml
- name: Create mempool containers
  register: output
  containers.podman.podman_containers:
    containers:
      - name: mempool-backend
        image: "mempool/backend:{{ mempool_version|default(latest) }}"
        state: present
        command: "./wait-for-it.sh {{ mempool_config.DATABASE_HOST }}:3306 --timeout=720 --strict -- ./start.sh"
        env: "{{ mempool_config }}"
        recreate: true
        volumes:
          - /var/compose/mempool/cache:/backend/cache
          - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
        ports:
          - "0.0.0.0:8999:8999"
      - name: mempool-frontend
        image: "mempool/frontend:{{ mempool_version|default(latest) }}"
        state: present
        ports:
          - "127.0.0.1:{{ mempool_http_port|default(4434)}}:8080"
#       command: "./wait-for {{ mempool_config.DATABASE_HOST }}:3306 --timeout=720 -- nginx -g 'daemon off;'"
        recreate: true
        env:
          FRONTEND_HTTP_PORT: "8080"
          BACKEND_MAINNET_HTTP_HOST: "host.containers.internal"
#         BACKEND_MAINNET_HTTP_HOST: "192.168.0.43"
#         BACKEND_MAINNET_HTTP_HOST: "mempool-backend"

- ansible.builtin.debug:
    var: output
  tags: upgrade

- name: Generate systemd unit file for mempool containers
  containers.podman.podman_generate_systemd:
    name: "{{ item }}"
    dest: ~/.config/systemd/user/
    wants: mariadb.service
  loop:
    - mempool-frontend
    - mempool-backend

- name: Ensure mempool containers are started and enabled
  ansible.builtin.systemd:
    name: "container-{{ item }}"
    scope: user
    daemon_reload: true
    state: started
    enabled: true
  loop:
    - mempool-frontend
    - mempool-backend
  # systemd won't see containers that are already running and we must use "state: present|started" in order to use recreate
  # and recreate is required for changes to mempool_config to take effect.
  failed_when: false