---
- name: Assert mempool secrets have been defined.
  ansible.builtin.assert:
    that:
      - item is defined
      - item != ''
    fail_msg: "FAILED: Secrets for mempool are not configured."
    quiet: true
  no_log: true
  loop:
    - "{{ mempool_core_rpc_pass }}"
    - "{{ mempool_db_pass }}"

- name: Clone the mempool repository
  ansible.builtin.git:
    repo: 'https://github.com/mempool/mempool.git'
    dest: "{{ ansible_env.HOME }}/src/mempool"
    version: "{{ mempool_version }}"
  register: git_repository

- name: Ensure mempool data directory.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /var/compose/mempool
    - "{{ ansible_env.HOME }}/.config/mempool/"

- name: Ensure writable cache directory.
  ansible.builtin.file:
    path: /var/compose/mempool/cache
    state: directory
    mode: '0777'

- name: Ensure a mempool environment variable file exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/mempool/env"
    state: touch
    mode: '0600'
  changed_when: false

# containers.podman.podman_container can't read env
#- name: Configure mempool variables
#  ansible.builtin.lineinfile:
#    path: "{{ ansible_env.HOME }}/.config/mempool/env"
#    regexp: "^{{ item.name }}"
#    line: "{{ item.name }}={{ item.value }}"
#  loop: "{{ mempool_environment }}"