---
- name: Install redis-server
  ansible.builtin.package:
    name:
      - redis-server
      - redis-tools
    state: present

- name: Configure redis-server to listen on a unix socket.
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: "{{ item.regexp }}" 
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^bind\s', line: 'bind 127.0.0.1 ::1 172.17.0.1' }
    - { regexp: '^unixsocket\s', line: 'unixsocket /var/run/redis/redis-server.sock' }
    - { regexp: '^unixsocketperm', line: 'unixsocketperm 777' }

- name: Copy redis-server systemd.service override file.
  ansible.builtin.copy:
    src: redis-server.service.d
    dest: /etc/systemd/system/
  register: systemd_service_override
  tags: systemd

- name: Run systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  when: systemd_service_override.changed
  tags: systemd
