---
# User scheme: $HOME/.local/bin
- name: Ensure Docker's python requirements are installed using the user scheme. 
  ansible.builtin.pip:
    name: 
    - docker>=6.0.0,<7.0.0
    - docker-compose>=1.29.0,<2.0.0
    - requests>=2.28.0,<3.0.0
    extra_args: --user

- name: Ensure a directory in the user home dir for docker-compose.
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/docker"
    state: directory

- name: Configure docker-compose.
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ ansible_env.HOME }}/docker/docker-compose.yml"
  tags: compose

- name: Create and start services
  community.docker.docker_compose:
    project_src: "{{ ansible_env.HOME }}/docker"
    build: true
  register: output
# when: git_repository.changed
  tags: upgrade

- ansible.builtin.debug:
    var: output
  tags: upgrade