---
# The following few tasks are for generating files containing secrets that are excluded from the repository.
- name: Ensure a secrets file for Tandoor exists.
  ansible.builtin.template:
    src: templates/tandoor.env.j2
    dest: "{{ ansible_env.HOME }}/docker/.env.tandoor"
    mode: '0600'
  tags: env, compose

- name: Ensure data directories for docker-compose containers.
  ansible.builtin.file:
    path: "/var/compose/{{ item }}"
    state: directory
  loop:
  - tandoor/staticfiles
  - tandoor/nginx_config
  - tandoor/mediafiles

- name: Tandoor wants to see the nginx configuration. No idea why.
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/nginx/conf.d/pancham.brenise.com.conf
    dest: /var/compose/tandoor/nginx_config/Recipes.cfg
