---
- name: Ensure writable PeerTube data and config directories.
  ansible.builtin.file:
    path:  "{{ item }}"
    state: directory
    mode: '0777'
  loop:
    - /var/compose/peertube/config
    - "{{ peertube_root_path }}/storage"
    - "{{ peertube_root_path }}/peertube-latest/client/dist"

#- name: Clone repository, in case we someday figure out how to workaround container builds failing.
#  ansible.builtin.git:
#    repo: 'https://github.com/Chocobozzz/PeerTube.git'
#    dest: /var/compose/peertube/src
#    version: "{{ peertube_version }}"
#  register: git_repository

- name: Configure environment variables
  ansible.builtin.template:
    src: peertube.env.j2
    dest: "{{ ansible_env.HOME }}/docker/.env.peertube"
    mode: '0600'
  tags: compose

- name: Configure PeerTube (docker)
  ansible.builtin.template:
    src: peertube_docker_production_yaml.j2
    dest: "/var/compose/peertube/config/production.yaml"
    mode: '0600'
  tags: settings

# For posterity:
#- name: Configure PeerTube (manual)
#  ansible.builtin.template:
#    src: peertube_manual_production.j2
#    dest: /var/www/peertube/config/production.yaml
#    mode: '0600'
#  tags: settings

# Not sure how to do "pure-lockfile" with the yarn module. It's supposed to be:
# yarn install --production --pure-lockfile
#- name: Build frontend client files using package.json in the repository.
#  community.general.yarn:
#    path: "{{ peertube_frontend_path }}"
#    production: true
## when: git_repository.changed
#  tags: yarn, upgrade
