---
nginx_strfry_https_port: 443
nginx_strfry_metrics_port: 4434
strfry_metrics_plugin_port: 8034
nginx_strfry_domain: bitcoiner.social
strfry_policies_enabled: no
strfry_relay:
  bind: "127.0.0.1"
  port: 8030
  nofiles: 65536
  realIpHeader: x-forwarded-for
  info:
    name: bitcoiner.social
    description: A fast, reliable, and up-to-date nostr relay with monitored server availability and nightly off-site backups.
    pubkey: ece3317bf8163930b5dafae50596b740b0608433b78568886a9a712a91a5d59b
    contact: nostr@bitcoiner.social
  maxWebsocketPayloadSize: 131072
  autoPingSeconds: 55
  enableTcpKeepalive: no
  queryTimesliceBudgetMicroseconds: 10000
  maxFilterLimit: 500
  maxSubsPerConnection: 20
  writePolicy:
    plugin: /var/lib/strfry/copmlex-entrypoint.ts
    lookbackSeconds: 0
  compression:
    enabled: yes
    slidingWindow: yes
  logging:
    dumpInAll: no
    dumpInEvents: no
    dumpInReqs: no
    dbScanPerf: no
    invalidEvents: yes
  numThreads:
    ingester: 3
    reqWorker: 3
    reqMonitor: 3
    negentropy: 2
  negentropy:
    enabled: no
    maxSyncEvents: 1000000
strfry_events:
  maxEventSize: 65536
  rejectEventsNewerThanSeconds: 900
  rejectEventsOlderThanSeconds: 94608000
  rejectEphemeralEventsOlderThanSeconds: 60
  ephemeralEventsLifetimeSeconds: 300
  maxNumTags: 2000
  maxTagValSize: 1024