---
- hosts: all
  become: yes

  roles:
    - role: bleetube.linux
      tags: linux
    - role: bleetube.dotfiles
      tags: dotfiles

- import_playbook: nginx/main.yml
- import_playbook: node_exporter.yml
- import_playbook: group_tasks/certbot/main.yml
- import_playbook: group_tasks/lego.yml
- import_playbook: group_tasks/mail.yml
- import_playbook: group_tasks/wireguard.yml
#- import_playbook: group_tasks/observability/main.yml # gantsign.golang throws an error _only_ when called from here?
- import_playbook: group_tasks/proxmox/main.yml
- import_playbook: group_tasks/mariadb.yml
- import_playbook: group_tasks/postgresql.yml
- import_playbook: group_tasks/podman.yml
#- import_playbook: group_tasks/docker.yml # migrated to podman
- import_playbook: group_tasks/synapse.yml
- import_playbook: group_tasks/strfry/main.yml
- import_playbook: group_tasks/jellyfin.yml
- import_playbook: host_tasks/metagross.offchain.pub/main.yml
- import_playbook: host_tasks/garchomp.bitcoiner.social/main.yml
#- import_playbook: host_tasks/rhyperior.bitcoiner.social/castopod.yml