--- # Run playbooks in a specific order
- import_playbook: linux.yml
- import_playbook: nginx/main.yml
- import_playbook: node_exporter.yml
##- import_playbook: group_tasks/certbot/main.yml # migrated to lego
- import_playbook: group_tasks/lego.yml
#- import_playbook: group_tasks/mail.yml # gather_facts getent passwd is broken when importing from here
- import_playbook: group_tasks/wireguard.yml
- import_playbook: group_tasks/observability/main.yml
##- import_playbook: group_tasks/proxmox/main.yml # needs testing
- import_playbook: group_tasks/mariadb.yml
- import_playbook: group_tasks/postgresql.yml
- import_playbook: group_tasks/podman.yml
##- import_playbook: group_tasks/docker.yml # migrated to podman
- import_playbook: group_tasks/synapse.yml
- import_playbook: group_tasks/strfry.yml
- import_playbook: group_tasks/jellyfin.yml
- import_playbook: host_tasks/sableye.satstack.cloud/redirect-homepage.yml
- import_playbook: host_tasks/pancham.brenise.com/peertube.yml
- import_playbook: host_tasks/rhyperior.bitcoiner.social/castopod.yml
- import_playbook: host_tasks/metagross.offchain.pub/strfry.yml
- import_playbook: host_tasks/garchomp.bitcoiner.social/strfry.yml
- import_playbook: host_tasks/garchomp.bitcoiner.social/hablanews.yml
- import_playbook: host_tasks/squirtle.satstack.net/lnd.yml
- import_playbook: host_tasks/squirtle.satstack.net/lego.yml
- import_playbook: host_tasks/wartortle.satstack.net/nextcloud/main.yml # needs monitoring
- import_playbook: host_tasks/wartortle.satstack.net/wikijs/main.yml
- import_playbook: host_tasks/wartortle.satstack.net/dojo.yml
#- import_playbook: host_tasks/wartortle.satstack.net/rtl/main.yml # this should be a role
#- import_playbook: host_tasks/wartortle.satstack.net/dojo_exporter/main.yml # this should be a role
#- import_playbook: host_tasks/wartortle.satstack.net/chat-with-gpt/main.yml # this should be a role
#- import_playbook: host_tasks/wartortle.satstack.net/changedetection/main.yml # this should be a role