---
- hosts: all
  become: yes

  roles:
    - role: bleetube.linux
      tags: linux
    - role: bleetube.dotfiles
      tags: dotfiles

- import_playbook: nginx/main.yml
- import_playbook: certbot/main.yml
- import_playbook: lego.yml
- import_playbook: node_exporter.yml
- import_playbook: mail.yml
- import_playbook: wireguard.yml
#- import_playbook: observability/main.yml # gantsign.golang throws an error _only_ when called from here?
- import_playbook: proxmox/main.yml
- import_playbook: mariadb.yml
- import_playbook: postgresql.yml
- import_playbook: podman.yml
- import_playbook: synapse.yml
- import_playbook: strfry/main.yml

# Tasks that are specific to the hosts they run on
- import_playbook: host_tasks/rhyperior.bitcoiner.social/castopod.yml