---
- hosts: mariadb
  become: true

  pre_tasks:
    - name: Assert all database passwords have been configured.
      ansible.builtin.assert:
        that:
          - item.password is defined
          - item.password != ''
        fail_msg: "FAILED: Database password for {{ item.name }} is not configured."
        quiet: true
      loop: "{{ mariadb_users }}"
      no_log: true

  roles:
    - role: fauust.mariadb
      tags: mariadb