---
- hosts: postgresql

  pre_tasks:
    - name: Assert all database passwords have been configured.
      ansible.builtin.assert:
        that:
          - item.pass is defined
          - item.pass != ''
        fail_msg: "FAILED: Database password for {{ item.name }} is not configured."
      loop: "{{ postgresql_users }}"
      no_log: true

# locale-gen en_US.UTF-8
# dpkg-reconfigure locales
  roles:
    - role: anxs.postgresql
      become: true
