---
- name: Configure nginx
  ansible.builtin.import_role:
    name: nginxinc.nginx_core.nginx_config
  tags: nginx
  become: true
  vars:
    # Each dictionary in the top level list/array represents a new configuration file.
    nginx_config_http_template_enable: true
    nginx_config_http_template:
      - template_file: http/default.conf.j2
        deployment_location: "/etc/nginx/conf.d/mappings.conf"
        backup: false
        config:
          map:
            mappings: # https://nginx.org/en/docs/http/websocket.html
              - string: $http_upgrade
                variable: $connection_upgrade
                content:
                  - value: default
                    new_value: upgrade
                  - value: "''"
                    new_value: close
      - template_file: http/default.conf.j2
        deployment_location: "/etc/nginx/conf.d/chatgpt_{{ inventory_hostname }}.conf"
        backup: false
        config:
          servers:
            - core:
                listen:
                  - address: "{{ default_interface_ipv4_address|default(ansible_default_ipv4.address) }}:4436 ssl http2"
                include:
                  - "/etc/nginx/acme_{{ inventory_hostname }}.conf"
              locations:
                - location: /
                  proxy:
                    pass: http://127.0.0.1:8036
                    http_version: '1.1'
                    set_header:
                      - field: Host
                        value: $http_host
                      - field: Connection
                        value: $connection_upgrade
                      - field: Upgrade
                        value: $http_upgrade