---
- name: Samourai | Assert all secrets have been defined.
  ansible.builtin.assert:
    that:
      - item is defined
      - item != ''
    fail_msg: "FAILED: Secrets are not configured."
    quiet: true
  no_log: true
  loop:
    - "{{ samourai_onion_address }}"
    - "{{ samourai_config.NODE_API_KEY }}"
    - "{{ samourai_config.NODE_ADMIN_KEY }}"
    - "{{ samourai_config.NODE_JWT_SECRET }}"
    - "{{ samourai_config.BITCOIND_RPC_PASSWORD }}"
    - "{{ samourai_config.MYSQL_PASSWORD }}"
  tags: env

- name: Samourai | Clone repository
  ansible.builtin.git:
    repo: 'https://code.samourai.io/dojo/samourai-dojo.git'
    dest: ~/src/samourai-dojo
    version: "{{ samourai_dojo_version }}"
  register: git_repository
  tags: upgrade

- name: Samourai | Check whether the database has been initialized
  community.mysql.mysql_info:
    filter:
      - databases
    return_empty_dbs: true
    login_user: "{{ samourai_environment.MYSQL_USER }}"
    login_password: "{{ samourai_config.MYSQL_PASSWORD }}"
  register: databases

- name: Samourai | Initialize database
  community.mysql.mysql_db:
    name: samourai
    state: import
    target: ~/src/samourai-dojo/db-scripts/1_db.sql.tpl
    login_user: "{{ samourai_config.MYSQL_USER }}"
    login_password: "{{ samourai_config.MYSQL_PASSWORD }}"
  when: databases.databases.samourai.size == 0