---
# https://matrix-org.github.io/synapse/latest/reverse_proxy.html
- name: Matrix Synapse | Configure nginx
  ansible.builtin.import_role:
    name: nginxinc.nginx_core.nginx_config
  vars:
    nginx_config_http_template_enable: true
    nginx_config_http_template:
      # See: https://github.com/binwiederhier/ntfy-ansible/blob/main/roles/nginx/templates/sites-available/ntfy.j2
      # Also, ntfy will not work in a subdirectory: https://github.com/binwiederhier/ntfy/issues/256
      - template_file: http/default.conf.j2
        deployment_location: "/etc/nginx/conf.d/ntfy_ntfy.bitcoiner.social.conf"
        backup: false
        config:
          upstreams:
            - name: ntfy
              servers:
                - address: unix:/var/lib/ntfy/ntfy.sock
          servers:
            - core:
                listen:
                  - address: "{{ default_interface_ipv4_address|default(ansible_default_ipv4.address) }}:443 ssl"
                    #http2: true
                include:
                  - "/etc/nginx/acme_ntfy.bitcoiner.social.conf"
                client_max_body_size: 0 # Stream request body to backend
              locations:
                - location: /
                  proxy:
                    pass: http://ntfy
                    http_version: '1.1'
                    set_header:
                      - field: Host
                        value: $http_host
                      - field: Connection
                        value: $connection_upgrade
                      - field: Upgrade
                        value: $http_upgrade
                      - field: X-Forwarded-For
                        value: $proxy_add_x_forwarded_for
                    connect_timeout: 3m
                    send_timeout: 3m
                    read_timeout: 3m
