---
- hosts: chesnaught.brenise.com

  vars:
    # Race condition, this picks the wireguard local address instead of the eno1 address.
#   lan_address: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
    lan_address: '192.168.0.44'

  vars_files:
    - vars/nginx.yml

  roles:
    - role: nginxinc.nginx_core.nginx_config
      tags: nginx
    - role: vharmers.jellyfin
      tags: jellyfin

  tasks:
    - import_tasks: tasks/install-doas.yml
      tags: doas

    - name: Copy nginx configuration for samourai.
      ansible.builtin.copy:
        src: nginx/conf.d/samourai.conf
        dest: /etc/nginx/conf.d/samourai_chesnaught.satstack.net.conf

# Variables do not carry over to imported playbooks.
- import_playbook: blee.yml
