---
- name: Configure nginx
  ansible.builtin.import_role:
    name: nginx_core.nginx_config
  tags: nginx
  become: true
  vars:
    # Each dictionary in the top level list/array represents a new configuration file.
    nginx_config_http_template_enable: true
    nginx_config_http_template:

      # https://grafana.com/tutorials/run-grafana-behind-a-proxy/#configure-nginx
      - template_file: http/default.conf.j2
        deployment_location: "/etc/nginx/conf.d/observability_{{ inventory_hostname }}.conf"
        backup: false
        config:
          servers:
            - core:
                listen:
                  - address: "{{ default_interface_ipv4_address|default(ansible_default_ipv4.address) }}:443 ssl"
                include:
                  - "/etc/nginx/acme_{{ inventory_hostname }}.conf"
              http2:
                enabled: true
              log:
                access:
                  - off
              locations:
                - location: /
                  proxy:
                    pass: "http://127.0.0.1:3000"
                    http_version: '1.1'
                    set_header:
                    - field: Host
                      value: $http_host
                - location: /api/live/
                  proxy:
                    pass: "http://127.0.0.1:3000"
                    http_version: '1.1'
                    set_header:
                    - field: Host
                      value: $http_host
                    - field: Connection
                      value: $connection_upgrade
                    - field: Upgrade
                      value: $http_upgrade
                - location: /public
                  core:
                    alias: /usr/share/grafana/public
                # https://www.robustperception.io/using-external-urls-and-proxies-with-prometheus/
                - location: /prometheus/
                  proxy:
                    pass: "http://127.0.0.1:9090/prometheus/"
                    http_version: '1.1'
                    set_header:
                    - field: Host
                      value: $http_host
                - location: /alertmanager/
                  proxy:
                    pass: "http://127.0.0.1:9093/alertmanager/"
                    http_version: '1.1'
                    set_header:
                    - field: Host
                      value: $http_host

      - template_file: http/default.conf.j2
        deployment_location: "/etc/nginx/conf.d/blackbox_exporter_{{ inventory_hostname }}.conf"
        backup: false
        config:
          servers:
            - core:
                listen:
                  - address: "{{ default_interface_ipv4_address|default(ansible_default_ipv4.address) }}:4431 ssl"
                include:
                  - "/etc/nginx/acme_{{ inventory_hostname }}.conf"
              locations:
                - location: /
                  proxy:
                    pass: "http://127.0.0.1:4431"
                    http_version: '1.1'

      # See: https://github.com/binwiederhier/ntfy-ansible/blob/main/roles/nginx/templates/sites-available/ntfy.j2
      # Also, ntfy will not work in a subdirectory: https://github.com/binwiederhier/ntfy/issues/256
      - template_file: http/default.conf.j2
        deployment_location: "/etc/nginx/conf.d/ntfy_{{ inventory_hostname }}.conf"
        backup: false
        config:
          upstreams:
            - name: ntfy
              servers:
                - address: unix:/var/lib/ntfy/ntfy.sock
          servers:
            - core:
                listen:
                  - address: "{{ default_interface_ipv4_address|default(ansible_default_ipv4.address) }}:4432 ssl"
                include:
                  - "/etc/nginx/acme_{{ inventory_hostname }}.conf"
                client_max_body_size: 0 # Stream request body to backend
              locations:
                - location: /
                  proxy:
                    pass: http://ntfy
                    http_version: '1.1'
                    set_header:
                      - field: Host
                        value: $http_host
                      - field: Connection
                        value: $connection_upgrade
                      - field: Upgrade
                        value: $http_upgrade
                      - field: X-Forwarded-For
                        value: $proxy_add_x_forwarded_for
                    connect_timeout: 3m
                    send_timeout: 3m
                    read_timeout: 3m
      - template_file: http/default.conf.j2
        deployment_location: "/etc/nginx/conf.d/ntfy-alertmanager_{{ inventory_hostname }}.conf"
        backup: false
        config:
          servers:
            - core:
                listen:
                  - address: "{{ default_interface_ipv4_address|default(ansible_default_ipv4.address) }}:4433 ssl"
                include:
                  - "/etc/nginx/acme_{{ inventory_hostname }}.conf"
              locations:
                - location: /
                  proxy:
                    pass: http://127.0.0.1:8033
                    http_version: '1.1'
                    set_header:
                      - field: Host
                        value: $http_host
