---
collections:

  - name: nginxinc.nginx_core
    src: https://github.com/nginxinc/ansible-collection-nginx
#   version: '>=0.6.0,<1.0.0'

  - name: prometheus.prometheus
    src: https://github.com/prometheus-community/ansible
#   version: '>=0.5.0,<1.0.0'

roles:

# - name: bleetube.dotfiles
#   src:  https://github.com/bleetube/ansible-role-dotfiles

# - name: bleetube.lego
#   src:  https://github.com/bleetube/ansible-role-lego

# - name: bleetube.linux
#   src:  https://github.com/bleetube/ansible-role-linux

# - name: bleetube.lego
#   src:  https://github.com/bleetube/ansible-role-lego

# - name: bleetube.wireguard
#   src:  https://github.com/bleetube/ansible-role-wireguard

# - name: bleetube.mail
#   src:  https://github.com/bleetube/ansible-role-mail

  - name: bleetube.ntfy
    src:  https://github.com/bleetube/ansible-role-ntfy

  - name: bleetube.ntfy-alertmanager
    src:  https://github.com/bleetube/ansible-role-ntfy-alertmanager

  - name: oefenweb.postfix
    src:  https://github.com/bleetube/ansible-role-postfix

  - name: geerlingguy.certbot
    src:  https://github.com/geerlingguy/ansible-role-certbot

  # requires commenting out warn in tasks/dashboards.yml
  - src:  https://github.com/cloudalchemy/ansible-grafana
    name: cloudalchemy.grafana
