---
collections:

  - name: nginxinc.nginx_core
    src: https://github.com/nginxinc/ansible-collection-nginx
#   version: '>=0.6.0'

  - name: prometheus.prometheus
    src: https://github.com/prometheus-community/ansible
#   version: '>=0.5.0'

  - name: containers.podman
    src: https://github.com/containers/ansible-podman-collections
#   version: '>=1.10.2'

# - name: community.docker
#   version: '>=3.4.8'

roles:

  - name: bleetube.dotfiles
    src:  https://github.com/bleetube/ansible-role-dotfiles

  - name: bleetube.linux
    src:  https://github.com/bleetube/ansible-role-linux

  - name: bleetube.lego
    src:  https://github.com/bleetube/ansible-role-lego

  - name: bleetube.wireguard
    src:  https://github.com/bleetube/ansible-role-wireguard

  - name: robertdebock.dovecot
    src:  https://github.com/robertdebock/ansible-role-dovecot

# - name: bleetube.disposable-mail
#   src:  https://github.com/bleetube/ansible-role-disposable-mail

  - name: bleetube.ntfy
    src:  https://github.com/bleetube/ansible-role-ntfy

  - name: bleetube.ntfy-alertmanager
    src:  https://github.com/bleetube/ansible-role-ntfy-alertmanager

  - name: bleetube.nextcloud
    src:  https://github.com/bleetube/ansible-role-nextcloud

  - name: bleetube.wikijs
    src:  https://github.com/bleetube/ansible-role-wikijs

  - name: bleetube.jellyfin
    src:  https://github.com/bleetube/ansible-role-jellyfin

  - name: geerlingguy.certbot
    src:  https://github.com/geerlingguy/ansible-role-certbot

  # requires commenting out warn in tasks/dashboards.yml
  - src:  https://github.com/cloudalchemy/ansible-grafana
    name: cloudalchemy.grafana

# - src:  https://github.com/haxorof/ansible-role-docker-ce
#   name: haxorof.docker_ce
#   version: '>=5.0.0'

  - src: https://github.com/alvistack/ansible-role-podman
    name: alvistack.podman
#   version: '>=5.4.0'

  - src: https://github.com/fauust/ansible-role-mariadb
    name: fauust.mariadb

  # two problems remaining with this role are the necessary workaround var and the deprecated apt_key usage.
# - src: https://github.com/ANXS/postgresql
  - src: https://github.com/VladDm93/postgresql
    version: postgres-14-15-support
    name: anxs.postgresql

  - src: https://github.com/JensTimmerman/ansible-role-vaultwarden
    name: jenstimmerman.vaultwarden
#   version: '>=1.1.0'

  # includes a minor change that skips the outdated apt role dependency
  - src: https://github.com/bleetube/ansible-role-onion
    name: systemli.onion
    version: skip_apt_key
#   version: '>=2.3.0'
