---
- hosts: wartortle.brenise.com
  become_user: "{{ sysadmin_username }}"
  become: true

  pre_tasks:
    - name: Assert mempool secrets have been defined.
      ansible.builtin.assert:
        that:
          - item is defined
          - item != ''
        fail_msg: "FAILED: Secrets for mempool are not configured."
        quiet: true
      no_log: true
      loop:
        - "{{ mempool_core_rpc_password }}"
        - "{{ mempool_db_password }}"
      tags: env

  tasks:
    - name: Configure environment variables
      ansible.builtin.template:
        src: mempool.env.j2
        dest: "{{ ansible_env.HOME }}/docker/.env.mempool"
        mode: '0600'
      tags: env

    - name: Clone repository
      ansible.builtin.git:
        repo: 'https://github.com/mempool/mempool.git'
        dest: "{{ ansible_env.HOME }}/src/mempool"
        version: "{{ mempool_version }}"
      register: git_repository
      tags: upgrade

    - name: Ensure data directory.
      ansible.builtin.file:
        path: /var/compose/mempool
        state: directory

    - name: Ensure writable cache directory.
      ansible.builtin.file:
        path: /var/compose/mempool/cache
        state: directory
        mode: '0777'
