---
- hosts: mariadb
# TODO: mysql_secure_installation

  pre_tasks:
    - name: Assert all database passwords have been configured.
      ansible.builtin.assert:
        that:
          - item.password is defined
          - item.password != ''
        fail_msg: "FAILED: Database password for {{ item.name }} is not configured."
        quiet: true
      loop: "{{ mariadb_users }}"
      no_log: true

#     ansible.builtin.fail:
#       msg: "FAILED: Database password for {{ item.name }} is not configured."
#     when: "item.password == ''"
#     loop: "{{ mariadb_users }}"

  roles:
    - role: fauust.mariadb
      tags: mariadb