---
acme_domains:
  - pancham.brenise.com
  - matrix.brenise.com
  - brenise.com
nginx_config_http_template_enable: true
nginx_config_http_template:
  # pancham.brenise.com jitsi
# - template_file: http/default.conf.j2
#   deployment_location: "/etc/nginx/conf.d/jitsi_{{ acme_domains[0] }}.conf"
#   backup: false
#   config:
#     servers:
#       - core:
#           listen:
#             - address: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:443 ssl http2"
#           include:
#             - "/etc/nginx/acme_{{ acme_domains[0] }}.conf"
#         log:
#           access:
#             - off
#         locations:
#           - location: /
#             proxy:
#               pass: "http://127.0.0.1:8000"
#               http_version: '1.1'
#               set_header:
#                - field: Host
#                  value: $http_host
#                - field: X-Forwarded-Proto
#                  value: $scheme
  # pancham.brenise.com tandoor
  - template_file: http/default.conf.j2
    deployment_location: "/etc/nginx/conf.d/tandoor_{{ acme_domains[0] }}.conf"
    backup: false
    config:
      servers:
        - core:
            listen:
              - address: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:4432 ssl http2"
            include:
              - "/etc/nginx/acme_{{ acme_domains[0] }}.conf"
          log:
            access:
              - off
          locations:
            - location: /
              proxy:
                pass: "http://127.0.0.1:4432"
                http_version: '1.1'
                set_header:
                 - field: Host
                   value: $http_host
                 - field: X-Forwarded-Proto
                   value: $scheme
            - location: /static
              core:
                alias: /var/compose/tandoor/staticfiles
            - location: /media
              core:
                alias: /var/compose/tandoor/mediafiles
  - template_file: http/default.conf.j2
    deployment_location: "/etc/nginx/conf.d/mappings.conf"
    backup: false
    config:
      map:
        mappings: # https://nginx.org/en/docs/http/websocket.html
          - string: $http_upgrade
            variable: $connection_upgrade
            content:
              - value: default
                new_value: upgrade
              - value: "''"
                new_value: close
  # matrix.brenise.com synapse
  - template_file: http/default.conf.j2
    deployment_location: "/etc/nginx/conf.d/{{ acme_domains[1] }}.conf"
    backup: false
    config:
      servers:
        - core:
            listen:
              - address: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:443 ssl http2"
              # For the federation port
              - address: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:8448 ssl http2"
            include:
              - "/etc/nginx/acme_{{ acme_domains[1] }}.conf"
            client_max_body_size: 50M
          log:
            access:
              - off
          locations:
            - location: '~ ^(/_matrix|/_synapse/client)'
              proxy:
                pass: "http://127.0.0.1:8008"
                http_version: '1.1'
                set_header:
                 - field: Host
                   value: $http_host
                 - field: X-Forwarded-For
                   value: $remote_addr
                 - field: X-Forwarded-Proto
                   value: $scheme
#           - location: '~ ^(/_health|/_synapse\/admin)'
            - location: /health
              proxy:
                pass: "http://127.0.0.1:8008"
                http_version: '1.1'
                set_header:
                 - field: Host
                   value: $http_host
                 - field: X-Forwarded-For
                   value: $remote_addr
                 - field: X-Forwarded-Proto
                   value: $scheme

  # brenise.com
  - template_file: http/default.conf.j2
    deployment_location: "/etc/nginx/conf.d/{{ acme_domains[2] }}.conf"
    backup: false
    config:
      servers:
        - core:
            listen:
              - address: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:443 ssl http2"
            include:
              - "/etc/nginx/acme_{{ acme_domains[2] }}.conf"
          log:
            access:
              - off
          locations:
            # https://matrix-org.github.io/synapse/latest/delegate.html
            - location: '= /.well-known/matrix/server'
              rewrite: # https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite
                return:
                  code: 200
                  text: >
                    '{"m.server":"matrix.brenise.com:443"}'
            - location: /static
              core:
                alias: /var/www/static
        # nfty, see: https://docs.ntfy.sh/config/#nginxapache2caddy
        - core:
            listen:
              - address: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:4434 ssl http2"
            include:
              - "/etc/nginx/acme_{{ acme_domains[2] }}.conf"
            client_max_body_size: 0
          log:
            access:
#             - off
              - path: "/var/log/nginx/access.log"
                format: main
          locations:
            - location: /
              proxy:
                pass: "http://127.0.0.1:2586"
                http_version: '1.1'
                buffering: false
                request_buffering: false
                redirect: false
                set_header:
                 - field: Host
                   value: $http_host
                 - field: X-Forwarded-For
                   value: $remote_addr
                 - field: Connection
                   value: $connection_upgrade
                 - field: Upgrade
                   value: $http_upgrade
                connect_timeout: 3m
                send_timeout: 3m
                read_timeout: 3m
            - location: '~ ^(/_matrix|/_synapse/client)'
              rewrite:
                return:
                  url: "https://matrix.bitcoiner.social$request_uri"
                  code: 301