---
- name: lnbits | Configure nginx
  ansible.builtin.import_role:
    name: nginx_core.nginx_config
  vars:
    nginx_config_http_template_enable: true
    nginx_config_http_template:
      - template_file: http/default.conf.j2
        deployment_location: "/etc/nginx/conf.d/lnbits_{{ nginx_lnbits_domain|default(inventory_hostname) }}.conf"
        backup: false
        config:
          servers:
            - core:
                listen:
                  - address: "{{ default_interface_ipv4_address|default(ansible_default_ipv4.address) }}:{{ nginx_lnbits_https_port|default(4432) }} ssl"
                include:
                  - "/etc/nginx/acme_{{ nginx_lnbits_domain|default(inventory_hostname) }}.conf"
                root: "{{ lnbits_root_path|default('/var/www/lnbits') }}"
              http2:
                enabled: yes
              locations:
                - location: /
                  proxy:
                    pass: http://127.0.0.01:{{ lnbits_port|default(5000) }}
                    http_version: '1.1'
                    set_header:
                      - field: Host
                        value: $http_host
                      - field: Connection
                        value: $connection_upgrade
                      - field: Upgrade
                        value: $http_upgrade
                    connect_timeout: 10m
                    send_timeout: 10m
                    read_timeout: 10m
              locations:
                - location: ~ ^/(static|core/static)/
                  core:
                    try_files:
                      files: $uri $uri/
                      code: =404

# not sure if we need this
# root /var/www/lnbits/lnbits;
#  location ~* \.(woff2)$ {
#       proxy_pass http://127.0.0.1:3007;
#       add_header Access-Control-Allow-Origin *;
#   }  