---
- hosts: sudo

  tasks:
    - name: Create an ansible user
      ansible.builtin.user:
        name: ansible
        home: /var/lib/ansible
        shell: /bin/bash
        createhome: yes
        state: present

    - name: Add ansible user to sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
        create: true
