---
- hosts: sableye.satstack.cloud
  tasks:
    - name: Configure a domain redirect and well-known pointers.
      ansible.builtin.import_role:
        name: nginx_core.nginx_config
      tags: nginx
      become: true
      vars:
        nginx_homepage_domain: satstack.cloud # used below
        nginx_config_http_template_enable: true
        nginx_config_http_template:
          - template_file: http/default.conf.j2
            deployment_location: "/etc/nginx/conf.d/{{ nginx_homepage_domain }}.conf"
            backup: false
            config:
              servers:
                - core:
                    listen:
                      - address: "{{ default_interface_ipv4_address|default(ansible_default_ipv4.address) }}:443 ssl"
                      # We also need to redirect federation requests to the synapse server.
                      - address: "{{ default_interface_ipv4_address|default(ansible_default_ipv4.address) }}:8443 ssl"
                    include:
                      - "/etc/nginx/acme_{{ nginx_homepage_domain }}.conf"
                  log:
                    access:
                      - off
                  locations:
                    - location: = /
                      rewrite:
                        return:
                          url: "https://github.com/bleetube/satstack"
                          code: 301
                    - location: /static
                      core:
                        alias: /var/www/static
                    - location: /.well-known/nostr.json
                      core:
                        alias: /var/www/static/nostr.json
                      headers:
                        add_headers:
                          - name: Access-Control-Allow-Origin
                            value: '*'
                    # https://matrix-org.github.io/synapse/latest/delegate.html
                    - location: '= /.well-known/matrix/server'
                      rewrite: # https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite
                        return:
                          code: 200
                          text: >
                            '{"m.server":"matrix.satstack.cloud:443"}'
                    - location: '~ ^(/_matrix|/_synapse/client)'
                      rewrite:
                        return:
                          url: "https://matrix.{{ nginx_homepage_domain }}$request_uri"
                          code: 301
                    # lightning address server (satdress)
                    - location: /.well-known/lnurlp/
                      headers:
                        add_headers: # web-based nostr clients need cors
                          - name: Access-Control-Allow-Origin
                            value: '*'
                      proxy:
                        pass: "http://10.19.21.42:8037"
                        set_header:
                        - field: Host
                          value: $http_host

          - template_file: http/default.conf.j2
            deployment_location: "/etc/nginx/conf.d/http_{{ nginx_homepage_domain }}.conf"
            backup: false
            config:
              servers:
                - core:
                    server_name: "{{ nginx_homepage_domain }}"
                    listen:
                      - address: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:80"
                  log:
                    access:
                      - off
                  locations:
                    - location: = /
                      rewrite:
                        return:
                          url: "https://github.com/bleetube/satstack"
                          code: 301
                    - location: /
                      rewrite:
                        return:
                          url: "https://{{ nginx_homepage_domain }}$request_uri"
                          code: 301