---
# https://github.com/ANXS/postgresql/blob/master/defaults/main.yml
postgresql_version: 15

postgresql_listen_addresses: 
 - ''
#- "172.17.0.1" # host.docker.internal
postgresql_autovacuum: on
postgresql_synchronous_commit: off
postgresql_password_encryption: scram-sha-256
postgresql_default_auth_method_hosts: scram-sha-256

# pgtune automation is broken.
# https://github.com/ANXS/postgresql/issues/201
#postgresql_pgtune: true
# Use the web app and prefix each variable with postgresql_
# https://pgtune.leopard.in.ua/

# DB Version: 13
# OS Type: linux
# DB Type: web
# Total Memory (RAM): 1 GB
# CPUs num: 2
# Data Storage: ssd

postgres_max_connections: 200
postgres_shared_buffers: 256MB
postgres_effective_cache_size: 768MB
postgres_maintenance_work_mem: 64MB
postgres_checkpoint_completion_target: 0.9
postgres_wal_buffers: 7864kB
postgres_default_statistics_target: 100
postgres_random_page_cost: 1.1
postgres_effective_io_concurrency: 200
postgres_work_mem: 1310kB
postgres_min_wal_size: 1GB
postgres_max_wal_size: 4GB
postgres_max_worker_processes: 2
postgres_max_parallel_workers_per_gather: 1
postgres_max_parallel_workers: 2
postgres_max_parallel_maintenance_workers: 1

# Authentication (pg_hba.conf)
postgresql_pg_hba_default:
  - { type: local, database: all, user: postgres, address: "", method: peer, comment: '"local" is for Unix domain socket connections only' }
  - { type: local, database: all, user: all, address: "", method: "{{ postgresql_default_auth_method_hosts }}", comment: '"local" is for Unix domain socket connections only' }
  - { type: host,  database: all, user: all, address: "127.0.0.1/32", method: "{{ postgresql_default_auth_method_hosts }}", comment: "IPv4 local connections:" }
  - { type: host,  database: all, user: all, address: "172.16.0.0/12", method: "{{ postgresql_default_auth_method_hosts }}", comment: "Docker container connections:"  }
  - { type: host,  database: all, user: all, address: "::1/128", method: "{{ postgresql_default_auth_method_hosts }}", comment: "IPv6 local connections:" }

# It's wierd they don't have a simple list for adding scram authentication: 
# https://github.com/ANXS/postgresql/blob/63a22322fdb769a4649aea3ff936ce6aea0d963a/templates/pg_hba.conf.j2#L28

# Troubleshoot authentication: tail -f /var/log/postgresql/postgresql-13-main.log
postgresql_users:
  - name: synapse
    pass: "{{ lookup('ansible.builtin.env', 'pancham_SYNAPSE_POSTGRES_PASSWORD') }}"
    encrypted: yes
    state: present
  - name: peertube
    pass: "{{ lookup('ansible.builtin.env', 'pancham_PEERTUBE_POSTGRES_PASSWORD') }}"
    encrypted: yes
    state: present
  - name: tandoor
    pass: "{{ lookup('ansible.builtin.env', 'pancham_TANDOOR_POSTGRES_PASSWORD') }}"
    encrypted: yes
    state: present

postgresql_databases:
  - name: synapse
    owner: synapse
    state: present
#   encoding: "UTF-8" # default
    lc_collate: C
    lc_ctype: C
  - name: peertube
    owner: peertube
    state: present
    pg_trgm: yes
    unaccent: yes
  - name: tandoor
    owner: tandoor
    state: present