---
wireguard_private_key: "{{ lookup('ansible.builtin.env', 'pancham_WIREGUARD_PRIVATE_KEY') }}"
wireguard_subnet: 10.17.21.0/24
wireguard_address: 10.17.21.1/24
wireguard_listen_port: 61420
wireguard_peers:
  - { allowed_ips: '10.17.21.10/32', public_key: 'F3XR83IgyTVANrQzpp81XagLCbC6vDkgT3lx5ETQJVA=' } # magikarp-nixbitcoin
