---
- hosts: wartortle.satstack.net

  tasks:
    # chat-with-gpt
    - import_tasks: ../containers/chat-with-gpt/setup.yml
    - import_tasks: ../containers/chat-with-gpt/podman.yml
      tags: podman
    - include_tasks:
        file: ../containers/chat-with-gpt/nginx_conf.yml
        apply:
          become: true
      tags: nginx