---
# https://matrix-org.github.io/synapse/latest/reverse_proxy.html
- name: Matrix Synapse | Configure nginx
  ansible.builtin.import_role:
    name: nginxinc.nginx_core.nginx_config
  vars:
    nginx_config_http_template_enable: true
    nginx_config_http_template:
      # matrix.bitcoiner.social synapse
      - template_file: http/default.conf.j2
        deployment_location: "/etc/nginx/conf.d/synapse_{{ synapse_domain }}.conf"
        backup: false
        config:
          servers:
            - core:
                listen:
                  - address: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:443 ssl"
                  # For the federation port
                  - address: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}:8448 ssl"
                include:
                  - "/etc/nginx/acme_{{ synapse_domain }}.conf"
                client_max_body_size: 50M
              log:
                access:
                  - off
              locations:
                - location: '~ ^(/_matrix|/_synapse/client)'
                  proxy:
                    pass: "http://127.0.0.1:8008"
                    http_version: '1.1'
                    set_header:
                    - field: Host
                      value: $http_host
                    - field: X-Forwarded-For
                      value: $remote_addr
                    - field: X-Forwarded-Proto
                      value: $scheme
                - location: /health
                  proxy:
                    pass: "http://127.0.0.1:8008"
                    http_version: '1.1'