---
- name: Configure environment variables
  ansible.builtin.template:
    src: mempool.env.j2
    dest: "{{ ansible_env.HOME }}/docker/.env.mempool"
    mode: '0600'
  tags: env

- name: Clone repository
  ansible.builtin.git:
    repo: 'https://github.com/mempool/mempool.git'
    dest: "{{ ansible_env.HOME }}/src/mempool"
    version: "{{ mempool_version }}"
  register: git_repository
  tags: upgrade

- name: Ensure data directory.
  ansible.builtin.file:
    path: /var/compose/mempool
    state: directory

- name: Ensure writable cache directory.
  ansible.builtin.file:
    path: /var/compose/mempool/cache
    state: directory
    mode: '0777'
